### Create - root category
POST http://localhost:8080/api/v1/partners/categories
Content-Type: application/json

{
  "name": "Insurance Partners",
  "display-order": 11
}

### Create - with parent
POST http://localhost:8080/api/v1/partners/categories
Content-Type: application/json

{
  "name": "Local Freight",
  "active": true,
  "display-order": 3,
  "parent-id": 25
}

### Create - validation error: blank name
POST http://localhost:8080/api/v1/partners/categories
Content-Type: application/json

{
  "name": "",
  "display-order": 0
}