CREATE TABLE product_variant_attributes
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version            BIGINT                                  NOT NULL DEFAULT 0,
    "order"            INTEGER                                 NOT NULL,
    variant_id         BIGINT                                  NOT NULL,
    attribute_value_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_product_variant_attributes PRIMARY KEY (id)
);

ALTER TABLE product_variant_attributes
    ADD CONSTRAINT uk_variant_attribute_order UNIQUE (variant_id, "order");

ALTER TABLE product_variant_attributes
    ADD CONSTRAINT uk_variant_attribute_value UNIQUE (variant_id, attribute_value_id);

ALTER TABLE product_variant_attributes
    ADD CONSTRAINT FK_PRODUCT_VARIANT_ATTRIBUTES_ON_ATTRIBUTE_VALUE FOREIGN KEY (attribute_value_id) REFERENCES product_attribute_values (id);

ALTER TABLE product_variant_attributes
    ADD CONSTRAINT FK_PRODUCT_VARIANT_ATTRIBUTES_ON_VARIANT FOREIGN KEY (variant_id) REFERENCES product_variants (id);