CREATE TABLE product_country_of_origins
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version BIGINT                                  NOT NULL DEFAULT 0,
    name    VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_product_country_of_origins PRIMARY KEY (id)
);

ALTER TABLE product_country_of_origins
    ADD CONSTRAINT uk_product_country_of_origin_name UNIQUE (name);