CREATE TABLE product_manufactures
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version BIGINT                                  NOT NULL DEFAULT 0,
    name    VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_product_manufactures PRIMARY KEY (id)
);

ALTER TABLE product_manufactures
    ADD CONSTRAINT uk_product_manufacture_name UNIQUE (name);