CREATE TABLE product_weight_measurements
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version   BIGINT                                  NOT NULL DEFAULT 0,
    unit      VARCHAR(10)                             NOT NULL,
    precision INTEGER                                 NOT NULL,
    scale     INTEGER                                 NOT NULL,
    CONSTRAINT pk_product_weight_measurements PRIMARY KEY (id)
);

ALTER TABLE product_weight_measurements
    ADD CONSTRAINT uk_product_weight_measurement_unit UNIQUE (unit);