CREATE TABLE product_additional_info
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version                BIGINT                                  NOT NULL DEFAULT 0,
    weight                 DECIMAL(19, 2),
    height                 DECIMAL(19, 2),
    depth                  DECIMAL(19, 2),
    dimension_type         VARCHAR(20),
    weight_measurement_id  BIGINT,
    product_manufacture_id BIGINT,
    country_of_origin_id   BIGINT,
    product_id             BIGINT                                  NOT NULL,
    CONSTRAINT pk_product_additional_info PRIMARY KEY (id)
);

ALTER TABLE product_additional_info
    ADD CONSTRAINT FK_PRODUCT_ADDITIONAL_INFO_ON_WEIGHT_MEASUREMENT FOREIGN KEY (weight_measurement_id) REFERENCES product_weight_measurements (id);

ALTER TABLE product_additional_info
    ADD CONSTRAINT FK_PRODUCT_ADDITIONAL_INFO_ON_PRODUCT_MANUFACTURE FOREIGN KEY (product_manufacture_id) REFERENCES product_manufactures (id);

ALTER TABLE product_additional_info
    ADD CONSTRAINT FK_PRODUCT_ADDITIONAL_INFO_ON_COUNTRY_OF_ORIGIN FOREIGN KEY (country_of_origin_id) REFERENCES product_country_of_origins (id);

ALTER TABLE product_additional_info
    ADD CONSTRAINT FK_PRODUCT_ADDITIONAL_INFO_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product_base_infos (id);

ALTER TABLE product_additional_info
    ADD CONSTRAINT uk_product_additional_info_product UNIQUE (product_id);

CREATE INDEX idx_product_additional_info_country_of_origin ON product_additional_info (country_of_origin_id);

CREATE INDEX idx_product_additional_info_manufacture ON product_additional_info (product_manufacture_id);

CREATE INDEX idx_product_additional_info_weight_measurement ON product_additional_info (weight_measurement_id);