CREATE TABLE product_barcodes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version    BIGINT                                  NOT NULL DEFAULT 0,
    value      VARCHAR(150)                            NOT NULL,
    type       VARCHAR(10)                             NOT NULL,
    variant_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_product_barcodes PRIMARY KEY (id)
);

ALTER TABLE product_barcodes
    ADD CONSTRAINT FK_PRODUCT_BARCODES_ON_VARIANT FOREIGN KEY (variant_id) REFERENCES product_variants (id);

ALTER TABLE product_barcodes
    ADD CONSTRAINT uk_product_barcode_value UNIQUE (value);