CREATE TABLE product_barcode_templates
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version BIGINT                                  NOT NULL DEFAULT 0,
    name    VARCHAR(30)                             NOT NULL,
    prefix  VARCHAR(30)                             NOT NULL,
    length  INTEGER                                 NOT NULL,
    CONSTRAINT pk_product_barcode_templates PRIMARY KEY (id)
);

ALTER TABLE product_barcode_templates
    ADD CONSTRAINT uk_product_barcode_template_prefix UNIQUE (prefix);