CREATE TABLE product_barcode_segments
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version        BIGINT                                  NOT NULL DEFAULT 0,
    name           VARCHAR(30)                             NOT NULL,
    segment        VARCHAR(20)                             NOT NULL,
    start_position INTEGER                                 NOT NULL,
    length         INTEGER                                 NOT NULL,
    decimals       INTEGER                                 NOT NULL,
    "order"        INTEGER                                 NOT NULL,
    template_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_product_barcode_segments PRIMARY KEY (id)
);

ALTER TABLE product_barcode_segments
    ADD CONSTRAINT FK_PRODUCT_BARCODE_SEGMENTS_ON_TEMPLATE FOREIGN KEY (template_id) REFERENCES product_barcode_templates (id);

ALTER TABLE product_barcode_segments
    ADD CONSTRAINT uk_barcode_segment_order UNIQUE (template_id, "order");