CREATE TABLE companies
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version      BIGINT  DEFAULT 0                       NOT NULL,
    name         VARCHAR(100)                            NOT NULL,
    name_en      VARCHAR(100),
    uic          VARCHAR(13)                             NOT NULL,
    vat          VARCHAR(12),
    custodian    VARCHAR(100)                            NOT NULL,
    custodian_en VARCHAR(100),
    type         VARCHAR(10)                             NOT NULL,
    active       BOOLEAN DEFAULT TRUE                    NOT NULL,
    CONSTRAINT pk_companies PRIMARY KEY (id)
);

ALTER TABLE companies
    ADD CONSTRAINT uk_company_name UNIQUE (name);

ALTER TABLE companies
    ADD CONSTRAINT uk_company_uic UNIQUE (uic);

ALTER TABLE companies
    ADD CONSTRAINT uk_company_vat UNIQUE (vat);

CREATE INDEX idx_company_type ON companies (type);