CREATE TABLE categories
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(100)                            NOT NULL,
    version       BIGINT                                  NOT NULL,
    active        BOOLEAN DEFAULT TRUE                    NOT NULL,
    display_order INTEGER                                 NOT NULL,
    parent_id     BIGINT,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

ALTER TABLE categories
    ADD CONSTRAINT FK_CATEGORIES_ON_PARENT FOREIGN KEY (parent_id) REFERENCES categories (id);

CREATE INDEX idx_category_name_active ON categories (name, active);
CREATE INDEX idx_category_parent_active ON categories (parent_id, active);
