CREATE TABLE categories
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version       BIGINT                                  NOT NULL DEFAULT 0,
    name          VARCHAR(100)                            NOT NULL,
    active        BOOLEAN                                 NOT NULL DEFAULT TRUE,
    display_order INTEGER                                 NOT NULL,
    parent_id     BIGINT,
    dtype         VARCHAR(10)                             NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

ALTER TABLE categories
    ADD CONSTRAINT FK_CATEGORIES_ON_PARENT FOREIGN KEY (parent_id) REFERENCES categories (id);

CREATE INDEX idx_category_name_active_dtype ON categories (name, active, dtype);
CREATE INDEX idx_category_parent_active_dtype ON categories (parent_id, active, dtype);
