CREATE TABLE product_types
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_product_types PRIMARY KEY (id)
);

ALTER TABLE product_types
    ADD CONSTRAINT uk_product_type_name UNIQUE (name);

INSERT INTO product_types (name)
VALUES ('STANDARD'),
       ('SERVICE'),
       ('PAYMENT');