CREATE TABLE products
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(100)                            NOT NULL,
    abbreviation    VARCHAR(20),
    description     VARCHAR(150),
    base_price      DECIMAL(19, 8)                          NOT NULL,
    active          BOOLEAN                                 NOT NULL,
    version         BIGINT                                  NOT NULL DEFAULT 0,
    product_type_id BIGINT                                  NOT NULL,
    category_id     BIGINT,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

ALTER TABLE products
    ADD CONSTRAINT uk_product_abbreviation UNIQUE (abbreviation);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_PRODUCT_TYPE FOREIGN KEY (product_type_id) REFERENCES product_types (id);

CREATE INDEX idx_product_name_active ON products (name, active);

CREATE INDEX idx_product_category ON products (category_id);