CREATE TABLE product_images
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url           VARCHAR(200)                            NOT NULL,
    display_order INTEGER                                 NOT NULL,
    is_primary    BOOLEAN                                 NOT NULL,
    version       BIGINT                                  NOT NULL DEFAULT 0,
    product_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_product_images PRIMARY KEY (id)
);

ALTER TABLE product_images
    ADD CONSTRAINT FK_PRODUCT_IMAGES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);

CREATE INDEX idx_image_product ON product_images (product_id);