CREATE TABLE product_measures
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version   BIGINT                                  NOT NULL DEFAULT 0,
    unit      VARCHAR(10)                             NOT NULL,
    precision INTEGER                                 NOT NULL,
    scale     INTEGER                                 NOT NULL,
    CONSTRAINT pk_product_measures PRIMARY KEY (id)
);

ALTER TABLE product_measures
    ADD CONSTRAINT uk_product_measures_unit UNIQUE (unit);

INSERT INTO product_measures (unit, precision, scale)
VALUES ('бр.', 10, 0),
       ('пак.', 10, 0),
       ('кут.', 10, 0),
       ('кг', 19, 3),
       ('гр.', 19, 3),
       ('л.', 19, 3),
       ('мл.', 19, 3),
       ('м.', 19, 3),
       ('см.', 19, 3);