CREATE TABLE product_base_infos
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version      BIGINT                                  NOT NULL DEFAULT 0,
    name         VARCHAR(100)                            NOT NULL,
    abbreviation VARCHAR(20),
    description  VARCHAR(150),
    base_price   DECIMAL(19, 8)                          NOT NULL,
    active       BOOLEAN                                 NOT NULL,
    type_id      BIGINT                                  NOT NULL,
    measure_id   BIGINT                                  NOT NULL,
    category_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_product_base_infos PRIMARY KEY (id)
);

ALTER TABLE product_base_infos
    ADD CONSTRAINT FK_PRODUCT_BASE_INFOS_ON_TYPE FOREIGN KEY (type_id) REFERENCES product_types (id);

ALTER TABLE product_base_infos
    ADD CONSTRAINT FK_PRODUCT_BASE_INFOS_ON_MEASURE FOREIGN KEY (measure_id) REFERENCES product_measures (id);

ALTER TABLE product_base_infos
    ADD CONSTRAINT FK_PRODUCT_BASE_INFOS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE product_base_infos
    ADD CONSTRAINT uk_product_abbreviation UNIQUE (abbreviation);

CREATE INDEX idx_product_name_active ON product_base_infos (name, active);

CREATE INDEX idx_product_base_infos_type ON product_base_infos (type_id);

CREATE INDEX idx_product_base_infos_measure ON product_base_infos (measure_id);

CREATE INDEX idx_product_category ON product_base_infos (category_id);