CREATE TABLE product_images
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version       BIGINT                                  NOT NULL DEFAULT 0,
    url           VARCHAR(200)                            NOT NULL,
    display_order INTEGER                                 NOT NULL,
    is_primary    BOOLEAN                                 NOT NULL,
    product_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_product_images PRIMARY KEY (id)
);

ALTER TABLE product_images
    ADD CONSTRAINT FK_PRODUCT_IMAGES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product_base_infos (id);

CREATE INDEX idx_product_image_product_id ON product_images (product_id);

CREATE UNIQUE INDEX uk_product_image_primary ON product_images (product_id) WHERE is_primary = true;