CREATE TABLE product_variants
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version          BIGINT                                  NOT NULL DEFAULT 0,
    sku              VARCHAR(20),
    additional_price DECIMAL(19, 8)                          NOT NULL,
    active           BOOLEAN                                 NOT NULL,
    product_id       BIGINT                                  NOT NULL,
    image_id         BIGINT,
    CONSTRAINT pk_product_variants PRIMARY KEY (id)
);

ALTER TABLE product_variants
    ADD CONSTRAINT uk_variant_sku UNIQUE (sku);

ALTER TABLE product_variants
    ADD CONSTRAINT FK_PRODUCT_VARIANTS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product_base_infos (id);

ALTER TABLE product_variants
    ADD CONSTRAINT FK_PRODUCT_VARIANTS_ON_IMAGE FOREIGN KEY (image_id) REFERENCES product_images (id);

CREATE INDEX idx_variant_product_active ON product_variants (product_id, active);

CREATE INDEX idx_variant_image ON product_variants (image_id);