CREATE TABLE product_attribute_keys
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version BIGINT                                  NOT NULL DEFAULT 0,
    name    VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_product_attribute_keys PRIMARY KEY (id)
);

ALTER TABLE product_attribute_keys
    ADD CONSTRAINT uk_product_attribute_key_name UNIQUE (name);