CREATE TABLE product_attribute_values
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version      BIGINT                                  NOT NULL DEFAULT 0,
    value        VARCHAR(50)                             NOT NULL,
    abbreviation VARCHAR(10)                             NOT NULL,
    key_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_product_attribute_values PRIMARY KEY (id)
);

ALTER TABLE product_attribute_values
    ADD CONSTRAINT FK_PRODUCT_ATTRIBUTE_VALUES_ON_KEY FOREIGN KEY (key_id) REFERENCES product_attribute_keys (id);

CREATE INDEX idx_product_attribute_values_value ON product_attribute_values (value);

CREATE INDEX idx_product_attribute_values_key ON product_attribute_values (key_id);