spring:
  application:
    name: stockify
  datasource:
    url: jdbc:postgresql://localhost:5432/stockify
    username: postgres
    password: P@ssword1
    driver-class-name: org.postgresql.Driver
  data:
    web:
      pageable:
        one-indexed-parameters: true
        max-page-size: 100
  threads:
    virtual:
      enabled: true
  mvc:
    apiversion:
      default: "1.0"
      supported: "1.0"
      use:
        header: "X-API-Version"
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  graphql:
    graphiql:
      enabled: true
      path: /graphiql

logging:
  level:
    # SQL заявки
    org.springframework.jdbc.core: TRACE
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE

    # Virtual threads
    org.springframework.web: DEBUG
    org.springframework.core.task: DEBUG

    # jOOQ
    org.jooq: DEBUG
    org.jooq.tools.LoggerListener: DEBUG

  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"